name: release

on:
  push:
    branches: [master]

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependencies
        run: |
          npm install yarn -g
          yarn

      - name: Build Application
        run: yarn build

      - name: Get Package Version
        uses: yunree/package-version@v1.0.2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: v${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Neural-${{ env.PACKAGE_VERSION }}.dmg
          asset_name: Neural-${{ env.PACKAGE_VERSION }}.dmg
          asset_content_type: application/octet-stream
